# Generated by Django 5.2.8 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0003_profile_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='active_connections',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='profile',
            name='membership_tier',
            field=models.CharField(choices=[('common', 'Common'), ('plus', 'Plus'), ('pro', 'Pro')], default='common', max_length=10),
        ),
        migrations.AddField(
            model_name='profile',
            name='remaining_connections',
            field=models.PositiveIntegerField(default=2),
        ),
    ]
