# Generated by Django 5.2.8 on 2025-12-01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0005_connection'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='last_connection_reset',
            field=models.DateField(blank=True, null=True),
        ),
    ]
