# Generated by Django 5.2.8 on 2025-12-01 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0006_profile_last_connection_reset'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='about',
            field=models.TextField(blank=True, default='About yourself'),
        ),
    ]
