# Generated by Django 5.2.8 on 2025-12-02 10:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0009_experience_is_current_experience_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='share_enabled',
            field=models.BooleanField(default=True),
        ),
    ]
