# Generated by Django 5.2.8 on 2025-12-05 01:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0010_profile_share_enabled'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_available',
            field=models.BooleanField(default=False),
        ),
    ]
