# Generated by Django 5.2.8 on 2025-12-05 02:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('profiles', '0011_profile_message_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='message_available_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
