# Generated by Django 5.2.8 on 2025-12-05 02:03

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('messaging', '0001_initial'),
        ('profiles', '0011_profile_message_available'),
    ]

    operations = [
        migrations.CreateModel(
            name='MessageDraft',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(blank=True, default='')),
                ('updated', models.DateTimeField(auto_now=True)),
                ('conversation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='drafts', to='messaging.conversation')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_drafts', to='profiles.profile')),
            ],
            options={
                'unique_together': {('profile', 'conversation')},
            },
        ),
    ]
